container:
  image: rust:latest

test_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  matrix:
    - build_script: cargo build --all-targets
    - build_script:
      - apt-get -y update && apt-get -y install libavformat-dev libavcodec-dev
      - cargo build --all-targets --features mp4_encoder
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
