[package]
name = "recorder"
version = "0.1.0"
authors = ["Jaro <jarohabiger@googlemail.com>"]
repository = "https://github.com/axiom-micro/recorder"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
indicatif = "0.15.0"
tiff-encoder = "0.3.2"
glob = "0.3.0"
rayon = "1.5.0"
anyhow = "1.0.34"
itertools = "0.9.0"
bytemuck = "1.4.1"
vulkano = { git = "https://github.com/apertus-open-source-cinema/vulkano", branch = "combined" }
vulkano-shaders = { git = "https://github.com/apertus-open-source-cinema/vulkano", branch = "combined" }
owning_ref = "0.4.1"
shlex = "0.1.1"
gstreamer = "0.16.5"
gstreamer-app = "0.16.5"
gstreamer-video = "0.16.5"
gstreamer-base = "0.16.5"

[profile.release]
debug = true
