[package]
name = "recorder"
version = "0.1.0"
authors = ["Jaro <jarohabiger@googlemail.com>"]
repository = "https://github.com/axiom-micro/recorder"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
indicatif = "0.15.0"
tiff-encoder = "0.3.2"
glob = "0.3.0"
rayon = "1.5.0"
anyhow = "1.0.34"
itertools = "0.9.0"
bytemuck = "1.4.1"
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"

[profile.release]
debug = true
